### ISSUE TITLE
make upstream dbuild friendly

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#15]
following projects are known to need patches -- turn our repos into something we can submit as a PR:

- [ ] adriaanm/framework.git#scala-2.11   // forked to make build dbuild friendly (only building lift-json)
- [x] adriaanm/json4s.git#scala-2.11   // forked to get rid of all sbt plugins that resulted in changes in the source code that refered to values generated by the buildinfo plugin
- [x] gkossakowski/parboiled.git#1.1.6-scala-2.11   // forked so I could remove problematic sbt plugins
- [x] gkossakowski/playframework.git#scala-2.11
- [ ] gkossakowski/scala-arm.git#v1.3-scala-2.11-compat
- [x] gkossakowski/scala-io.git#0.4.2-scala-2.11   // forked to: // 1. disable building of scaladoc docs (due to regression in scaladoc) // 2. add dependency on scala-parser-combinators //   3. remove use of sbteclipse plugin that Artifactory cannot resolve
- [x] gkossakowski/spray-json.git#1.2.5-scala-2.11   // forked so I could upgrade to sbt 0.13.1 and remove problematic sbt plugins
- [ ] gkossakowski/spray.git#1.3-scala-2.11   // forked so I could remove problematic sbt plugins
- [x] gkossakowski/twirl.git#scala-2.11
- [ ] retronym/browse.git#topic/2.11-compat

**Comment by SethTisue** [comment]
Adriaan has additional similar changes in https://github.com/adriaanm/community-builds/commits/2.11.x. “follow up to various upstream project to bump versions / drop dependencies on plugins that should not be in main repo” he says

**Comment by adriaanm** [comment]
looks like this list is outdated

**Comment by SethTisue** [comment]
we're more or less leaving the 2.11 builds alone these days (especially the JDK6 one). there is a new umbrella 2.12 ticket at https://github.com/scala/community-builds/issues/158
